### ISSUE TITLE
Should mention file order importance in modularity section.

### ISSUE THREAD

**Issue by ehutch79** [johnpapa/angularjs-styleguide#184]
When putting controllers in a file named 'thing.controller.js' and the module setter in a file named 'thing.module.js', issues arise when you blindly concat them with grunt. Specifically a  [$injector:nomod] error. The issue arising because getters end up in the file before the module setter.

It'd be helpful if this, and the solution, were at least mentioned in the grunt/gulp section.

the solution being to change your source from something like "['src/js/**/*.js']" to "['src/js/**/*.module.js','src/js/**/*.js']".

**Comment by philmerrell** [comment]
I was also confused about this and was relieved to see someone else had the same question.  I think a simple note in the [Naming Section](https://github.com/johnpapa/angularjs-styleguide#style-y121) in addition to more in depth description in the grunt/gulp section would suffice.

**Comment by johnpapa** [comment]
the naming was in the naming section, but it was short. I added a new section for gulp/grunt and task automation that i will fill out over time. here is the first bit 843e09fba18b306aca0fd0ff3bedd1cd4baa3a62
