### ISSUE TITLE
Is it necessary to use @ngInject if we religiously use $inject?

### ISSUE THREAD

**Issue by nareshbhatia** [johnpapa/angularjs-styleguide#212]
The section titled "Manually Identify Dependencies" states that:

> Use $inject to manually identify your dependencies for AngularJS components.
>
> Why?: This technique mirrors the technique used by ng-annotate, which I recommend for automating the creation of minification safe dependencies. If ng-annotate detects injection has already been made, it will not duplicate it."

Does this mean that if we religiously use `$inject` for all injections, there is no need to use `@ngInject`?

**Comment by nareshbhatia** [comment]
I notice that in your gulp-patterns project you are mostly using `@ngInject`. There are a few places though where `$inject` is used. Could you please provide some insight onto this guideline?

**Comment by johnpapa** [comment]
no, not if you cover all of the places. however its not always easy. THe comments never bother me and make it easy to catch later. its really about covering yourself.
