### ISSUE TITLE
Y075 (controllerAs in directives with isolated scope) example broken

### ISSUE THREAD

**Issue by fta1** [johnpapa/angularjs-styleguide#213]
In the provided example of style Y075, the myExample directive has an isolated scope with 'max' defined, and the directive is called with `max=77`. **If** the purpose of the example is to show that `vm.max == 77`, it is broken.. sort of.

As the scope is isolated, the provided code is incorrect but because of the way the associated controller ExampleController is written, the bug is masked.
If you remove the `vm.max = $scope.max;` line, then `vm.max` should be `undefined` (or `NaN` because of the `%i`), while one would expect it to equal `77`.
The reason is that the directive doesn't use `bindToController: true` which is mandatory for isolated scopes properties to be bound to the `this` (your vm) of controllers. 

From https://docs.angularjs.org/api/ng/service/$compile:
> bindToController
> When an isolate scope is used for a component (see above), and controllerAs is used,  `bindToController: true` will allow a component to have its properties bound to the controller, rather than to scope. When the controller is instantiated, the initial values of the isolate scope bindings are already available.

An example with an injection is good to have but using $scope here is sort of counter productive, or at least super confusing if you're new to this syntax.
Or maybe I misunderstood the purpose of the example...

**Comment by johnpapa** [comment]
`bindToController: true` should be there. Feel like making a PR?

**Comment by fta1** [comment]
I just did, PR #216

**Comment by johnpapa** [comment]
fixed in 5585ed34b0b4e62405fc8526a61cefe302259d3a
