### ISSUE TITLE
Ng-If versus Ng-Show

### ISSUE THREAD

**Issue by geovanisouza92** [johnpapa/angularjs-styleguide#218]
Reading [Performance com AngularJS](https://speakerdeck.com/willmendesneto/performance-com-angularjs?slide=27), the author say that ```ng-show``` doesn't show the element, but the bindings stay active.

Maybe this point, if true, could be clarified on styleguide, explaining that, if the dev want to choose between to extents of markup that will not change, is recommended to use ```ng-if```

**Comment by johnpapa** [comment]
Its a nice point, but its a not a "style".
