### ISSUE TITLE
vm in test cases

### ISSUE THREAD

**Issue by sanjay-patel** [johnpapa/angularjs-styleguide#226]
variables defined with vm
vm = this;
vm.var1 = 1;

now in jasmin test cases 
      $controller('RiskAnalysis', {
                $scope: scope,
       });

I can not access the scope.var1
For that should I need to use also
$scope.var1 = 1 in controller?

**Comment by Markionium** [comment]
Those vm variables are defined on the `this` which is in your case the controller object.

Therefore in your jasmine tests you can access those on the controller. The $controller function returns the controller object. On which you should be able to access the var1 variable.


The following should work.
```js
var riskAnalysisController = $controller('RiskAnalysis', {
    $scope: scope,
});

expect(riskAnalysisController.var1).toBe(1);
```
