### ISSUE TITLE
Why setting the same controller in both route config and template?

### ISSUE THREAD

**Issue by dietergeerts** [johnpapa/angularjs-styleguide#228]
I see that the controller for a template is defined in both the route config as the actual template. One of them is not needed I suppose, as there will be two of them created? Which would you keep and which would you remove? Removing it from the template messes up the IDE (IntelliJ IDEA), so I would say in the route config?

**Comment by johnpapa** [comment]
i have a style for that https://github.com/johnpapa/angularjs-styleguide#style-y038
