### ISSUE TITLE
get Form in controller

### ISSUE THREAD

**Issue by leonanluppi** [johnpapa/angularjs-styleguide#242]
Hello everybody,

How can i get my form in controller. For example:

<form name="my_form">
     <input type="text"/>
</form>

How can i get my_form, to set it pristine.

My controller is something like:
	angular.module("Proposal.Justification").controller("JustificationController", JustificationController);
	JustificationController.$inject = ["$scope", "JustificationFactory"];
	function JustificationController($scope, JustificationFactory) {
		var vm = this;
                vm.onInit = onInit;
		function onInit() {
			vm.my_form.$setPristine();
                }
        }

**Comment by johnpapa** [comment]
Please post angular questions to StackOverflow.

Thanks
