### ISSUE TITLE
AngularJs repository pattern on StyleGuide 

### ISSUE THREAD

**Issue by bcopmt143** [johnpapa/angularjs-styleguide#244]
I would like to thank for this styleguide... it is amazing and help me to write clean and maintainable code. 
My Data Services (Handle communication with the server) now growing up and reach to unmanageable state, and I get confused to use the repository pattern as shown on http://www.pluralsight.com/courses/build-apps-angular-breeze-part2,  

opinion  and additional Style guide for the repository patter ?

**Comment by johnpapa** [comment]
the repo pattern is good, but i dont think its appropriate for this style guide as it expands far beyond angular
