### ISSUE TITLE
how should I write my test if I'm using the `controller as` syntax

### ISSUE THREAD

**Issue by chenchengxing** [johnpapa/angularjs-styleguide#251]
For the code below, how can I test `activate` function?
```
/*
* recommend
* Using function declarations
* and bindable members up top.
*/
function Avengers(dataservice, logger) {
    var vm = this;
    vm.avengers = [];
    vm.getAvengers = getAvengers;
    vm.title = 'Avengers';

    activate();

    function activate() {
        return getAvengers().then(function() {
            logger.info('Activated Avengers View');
        });
    }

    function getAvengers() {
        return dataservice.getAvengers().then(function(data) {
            vm.avengers = data;
            return vm.avengers;
        });
    }
}
```

**Comment by johnpapa** [comment]
a few ways. you can test that when you create the controller that the logger displays the activated message ... or that the vm.avengers gets the data. you'd want to mock the data and stub the method calls, and not use the real data service.

**Comment by chenchengxing** [comment]
Thank you. I got it~

**Comment by getuliojr** [comment]
Here is another example that should help:

it("should assign My Movie as title", function () {
       var vm = controller("movieController", { $scope: scope });
       expect(vm.title).toBe("My Movie");
    });
