### ISSUE TITLE
Always use JavaScript in strict mode?

### ISSUE THREAD

**Issue by rayshan** [johnpapa/angularjs-styleguide#252]
Hello, just wondering what the consensus is amongst the Angular community.

**Comment by wardbell** [comment]
Do you mean JS strict mode or DI strict mode? JS strict I strongly endorse. DI strict I despise. 

I won't allow DI strict in my projects. It enshrines the annotation kruft in my code. Annotation for minification can and should be handled by tooling (ngAnnotate).

**Comment by rayshan** [comment]
Sorry should've clarified I meant JavaScript strict mode. Though I do agree with using `ngAnnotate`.

**Comment by johnpapa** [comment]
i do always use strict mode for javascript. just my preference. not really a style for this guide tho
