### ISSUE TITLE
Controller inside directive's closure

### ISSUE THREAD

**Issue by caspyin** [johnpapa/angularjs-styleguide#253]
In the section [Directives and ControllerAs - Y075](https://github.com/johnpapa/angularjs-styleguide#style-y075) the example used has the directive's controller outside the closure as recommended by [Manually Identify Dependencies - Y091](https://github.com/johnpapa/angularjs-styleguide#style-y091) in order to avoid `$inject` being unreachable. Y091 also says that you can avoid `$inject` being unreachable by "either moving the `$inject` above the return statement or by using the alternate array injection syntax".

Based on this, my primary question is as follows. Are there any negative consequences to defining the directives Controller **inside** the directives closure but **above the return statement**?  See code below. Specifically relating to testability or minification. Is there some other benefit to having the Controller outside the directive's closure?

```javascript
angular
  .module('app.reports')
  .directive('myExample', myExample);

function myExample () {
  var directive = {
    restrict: 'EA',
    replace: true,
    templateUrl: 'app/feature/example.directive.html',
    scope: {
      max: '@'
    }, 
    link: link,
    controller: Controller,
    controllerAs: 'vm'
    bindToController: true,     // required in 1.3+ with controllerAs
  };

  function link (scope, el, attr, controller) {
    console.log("executing link fn()");
  }

  Controller.$inject = ['$scope'];
  
  function Controller($scope) {
    var vm = this;
    console.log("executing controller fn()");
  };

  return directive;
};
```

Also a related question. I noticed that in using this style I can now use the generic "Controller" name for any directive's controller. Are there consequences with this doing that? Console errors are pretty clear that an error is in the Controller at the file path.

Thanks for all the hard work - this guide is immensely helpful!

**Comment by johnpapa** [comment]
You can certainly define the directive above the return statement and inside the closure. This is just my style.

Glad you like the guide!

**Comment by wardbell** [comment]
Know that you're controller is completely private to the directive. That's fine if you aren't going to test the controller and you might not need to do so because it's just private implementation. But if the controller has side-effects that you need to explore under test, then I think this approach makes such testing more difficult. At least I don't know how I'd test it ... not as I write this comment anyway,

**Comment by johnpapa** [comment]
Yep, Controller should be exposed outside the closure to be testable.

**Comment by caspyin** [comment]
Perfect! Thanks guys, that's exactly the type of thing I needed to know about this. Thanks again!

**Comment by enjoiful** [comment]
Great discussion regarding the nuances of placing a directive's controller inside or outside its closure.  Thanks for the insight.

**Comment by wardbell** [comment]
Well ... subsequent to my January post I learned how to get the controller from the directive itself while testing it. So it isn't the big deal I thought it was.  See the Adventures in Angular episode on ["Advanced Directives"](http://devchat.tv/adventures-in-angular/031-aia-advanced-directives)

**Comment by tirams** [comment]
I was about to ask the same question, thanks @wardbell for the link. So I can have access to the directive's controller for testing and keep it defined interal to the directive. I would reach my code coverage minimums otherwise.

**Comment by NicholasBoll** [comment]
For those of you wondering, like I was. This is how:
```JavaScript
inject(function (_fooDirective_) {
  var fooDirective = _fooDirective_;
  console.log(fooDirective.controller);
});
```
