### ISSUE TITLE
devel: true

### ISSUE THREAD

**Issue by robertdunaway** [johnpapa/angularjs-styleguide#266]
I'm still learning github.  What I really wanted to add was a comment, not an issue.

I'm adopting your jslint options for our standard.

When coming across browser functions like "alert", the jslint options flag alert as undefined.  I found that by adding "devel": true, to the options list will work with "browser": true to ignore alert.  I know, we don't use alert anymore but it's just an example.

I appreciate all your work.  You've saved me many hours and your plural site and Adventures in Angular are very helpful.  Thanks,
Bob

                "browser": true,
                "devel": true,      // in combination with "browser: true" allows things like "alert('hi');" to not be flagged as undefined.

**Comment by johnpapa** [comment]
thats a good tip, though I dont want to add that to the style guide as I dont encourage that flag for production code. but its a good tip for dev-time.

glad you like the style guide and i appreciate the feedback!

**Comment by robertdunaway** [comment]
You're right.  Thanks.




------ Original Message ------
   Received: 07:16 PM EST, 02/10/2015

**Comment by johnpapa** [comment]
no worries. this is a good tip still and i like that its here in the comments as others can find it :)
