### ISSUE TITLE
Standard function naming for directive, controller, service / factory, etc.?

### ISSUE THREAD

**Issue by jchandra74** [johnpapa/angularjs-styleguide#272]
Naming the implementation of the controller as **ctrlFn**, service as **serviceFn**, directive as **directiveFn**, etc.

Good idea or not?

Good reason:
* Easier to templatize
* One less name to remember and it's always the same for whatever service you created.

Bad probably because of the same reason...
* harder to use Find since everything is named the same thing? But then again, you can still search by using the angular name..., if it is one per file, might not be bad?

Example...
```javascript
//fooService
(function() {
  'use strict';

  angular.module('...')
    .factory('fooService', serviceFn);

  serviceFn.$inject = ['$http','$log',...];
  function serviceFn($http, $log, ...) {
    var service = {
       bar: bar
    };

    return service;

    function bar(...) {
       return $http.get('...');
    }
  }
}());
```

**Comment by johnpapa** [comment]
templates for tooling can adjust to custom names. i am not a fan of changing styles for tooling, i like the other way around.

all being the same name can be more difficult to debug too, when the error shows the function name 'serviceFn'

I prefer my code to follow readability, too.

does it work? sure. but i'm not a fan personally.
