### ISSUE TITLE
Inconsistent route errors example

### ISSUE THREAD

**Issue by filipesilva** [johnpapa/angularjs-styleguide#274]
Hi there,

I might be missing something, but the Route Errors example seems inconsistent
https://github.com/johnpapa/angularjs-styleguide#route-errors

There is a mention of going to the dashboard, and of an exit clause, but I mostly see the logging of errors in that code. Is it intended to be as is? That comment kinda looks like it was for another handler.

**Comment by johnpapa** [comment]
I am not sure I am following your question. Can you clarify please?

**Comment by filipesilva** [comment]
In the linked section, the first comment block on the code snippet  seems unrelated to the code itself. My question is if it is correct, or a copy paste error.

**Comment by johnpapa** [comment]
Thanks, I just fixed the code. I had comments in there for code I had removed. I decided that the full code was good to show.
