### ISSUE TITLE
Consider noting the new ES6/Traceur friendly ngAnnotate syntax

### ISSUE THREAD

**Issue by jimthedev** [johnpapa/angularjs-styleguide#279]
Hi John,

Thanks for your guide. I know you don't recommend using ngAnnotate but you do mention the ngAnnotate comment syntax `/** @ngInject **/`. Unfortunately this syntax is not forward compatible w/ES6 and Traceur. Would you consider changing this syntax to be the new directive style syntax `"ngInject";` that is discussed here:
https://github.com/olov/ng-annotate/issues/132

Thanks again!

**Comment by johnpapa** [comment]
Why do you think I dont use ngAnnotate? I think its awesome

I think that's fine for ES6.

**Comment by jimthedev** [comment]
Whoops, I saw this section first and assumed it was a recommendation: [Manual Annotating for Dependency Injection](https://github.com/johnpapa/angularjs-styleguide#manual-annotating-for-dependency-injection).

**Comment by johnpapa** [comment]
no worries, i thought i mistyped somewhere :)

i like your suggestion, but i dont want to update for es6 just yet

**Comment by jimthedev** [comment]
Sounds good. Thanks John.
