### ISSUE TITLE
File structure, sharing functions between two components

### ISSUE THREAD

**Issue by lvarayut** [johnpapa/angularjs-styleguide#282]
First of all, thanks for the great best practices. After reading, I have some questions about sharing some functions between two or more components. If I had a structure as following:

```
app/
----components/
--------student
------------studentFactory.js // Which has a function called getAllStudents()
--------report
------------reportFactory.js // Which also need the getAllStudents() function
```

I don't want them to depend on each other, in case that one component could be not used anymore in the future. In this case, how can I access the getAllStudents() function from report without DRY?

**Comment by dietergeerts** [comment]
We also have some modules which need to use certain service calls from each other. What we then do is split the module in two pieces, one with services (and their calls) that are only used by that module, and one with the calls that will be used by other modules, or you can just put those services in your core module.

**Comment by lvarayut** [comment]
@dietergeerts, Thanks so much for your explanation. That sounds good to me. However, in your case, if the user module was unplugged from the application, even through it's a rare case. The user service in the layout will be broken, right? Would it be possible to unplug the user module without affect to others? I mean that if I unplugged the user module, the layout module would show blank area instead of username without breaking the entire app.  Sorry for my curious, but if it was possible, it would be really nice.

**Comment by dietergeerts** [comment]
@lvarayut, It won't be broken, as the essential calls will be in the core module, not in the user module. That's the whole point. Some calls are essential to many other modules, and thus they need to be in the core module, or a separate one that you don't unplug, ever, as there will be dependencies. So as for user calls, the one that only gets the name to show in the layout can be found in the core module, all other calls, like getting the profile and settings etc... can be found in the user module. I hope that clarifies the setup?

**Comment by lvarayut** [comment]
@dietergeerts, very clear explanation. I got it! Thanks so much again for your help. I appreciated it.
