### ISSUE TITLE
Performance best practices

### ISSUE THREAD

**Issue by brutalcrozt** [johnpapa/angularjs-styleguide#291]
according to miskow presentation on [Angularjs MTV meetup Best Practices](https://www.youtube.com/watch?v=ZhfUv0spHCY) at 49:44

### he say that performance depend on 2 thing :

1. How many binding you have.
2. How expensive you getter. (should fast)

And i think that means simple and fast. In my comprehension ```getter``` mean a method in a service. But in my case a little bit complex.
So how make it simple? i guest it's not possible to change the algorithm? or just calling internal (private) function in a service? does it take effect?

### So here is my question :

1. Best practice to make ```getter``` on a method in service so will not cause memory leak.
  * I hope you can make an clear axample like in the style guide, and update to add this section to the style guide
2. How IIFE work ? Can you explain it to me?
3. How IIFE work on a function inside factory (method in service)? is it remove the global variable too? even if i use ```var```, like when we return a factory?

Sorry to brother you daddy :smiley: (papa means daddy in my country)

**Comment by johnpapa** [comment]
Good questions, but also pretty long answers :)

Your best bet is to take questions to StackOverflow. This repo is for the guide.
