### ISSUE TITLE
HowTo: Controller to Controller communication

### ISSUE THREAD

**Issue by raDiesle** [johnpapa/angularjs-styleguide#294]
As it seems to be a very diverse discussion:

How to achieve controller to controller communication in conjunction with services as model?

Solutions are in controller: 

* $rootScope.$watch 

*$rootScope.$broadcast("mynamingpattern" ...

* $rootScope.$emit(" ...

* $scope.$watch( function(myservice

* eventHandling: myService.listenToDataChangedHandler(function(){ ...

* promises and notification event

* or an angular independant messaging library

story continues how code in the service should look like.

How do you think?

**Comment by dietergeerts** [comment]
What kind of communication do you need? If it's just one-way like in a controller that's used inside the html of another controller, you can just use data-attributes on your element and get them in your controller.

**Comment by raDiesle** [comment]
Hi Dieter,
data-attributes is the jQuery way, but I assume definitely not the angular way. 
As described in this styleguide, it is recommanded to share state between services, which is a good idea !

**Comment by rasheedamir** [comment]
@raDiesle Here are my thoughts on cross component communication: http://www.slideshare.net/rasheedwaraich/angular-js-recommended-practices-mini

You can go through slide # 16 to slide # 21.

**Comment by raDiesle** [comment]
Thanks @rasheedamir . Similar fundamental thoughts I have, 
but it requires more clarification: code ! , situation to use, more pro-con,

I think it is too common summarized to put into a styleguide, but a great start for explanation.

How do you think? Something which should go into styleguide ?

**Comment by dietergeerts** [comment]
@raDiesle , I don't think so. When you already have your item, and the subcontroller is used for a part of that item or a subitem of it, it's far better to just use an attribute to 'give' that to your controller. How else are you gonna set the item? You need to have some sort of identifier or the object itself. Unless you hold global states, which is bad, you can't use anything else here....

**Comment by johnpapa** [comment]
It depends. Controller-->  sub-Controller doesn't require anything. Directives use isolate scopes (or not).

It really comes down to 2 controllers without a defined relationship. Yes you can use messaging (broadcast/emit), bur I prefer not to spam my app and its fire and forget. If I want the message to get there, I use a service/factory.

I'm not sure this is a style. I see this more as a tip. And its not one way, there are other ways too.

Closing

**Comment by rasheedamir** [comment]
@raDiesle 

you might like this: http://www.aurorasolutions.io/angularjs-cross-component-communication/

one of my team members posted article on the topic "AngularJS Cross Component Communication"
