### ISSUE TITLE
naming conventions and recommendation for location of files for end-to-end tests are missing

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angularjs-styleguide#77]

**Comment by jeserkin** [comment]
I might also add, that `Factory Names` section says, that
> Use camel-casing for services and factories.
But at the same time it doesn't tell whether it should start with capital letter or not. And if so (since most objects do), then `logger` example should be `Logger`, right?

**Comment by jeserkin** [comment]
Also regarding naming. Should there be provider type placed at the end for clarity?
* So if `Logger` is a factory, then `Logger` (only exception IMHO, but maybe it should have type at the end as well)
* If `Logger` is service, then `LoggerService`

**Comment by johnpapa** [comment]
I prefer services/factories to be camelCase but its a preference, not a rule. I like camelCase because they are singletons that get instantiated once, while controllers are newed up each time.

You can add the suffix to the service or factory. again its not a rule either way. Sometimes its obvious what it is, so I leave it off. Other times it is less obvious.

**Comment by jeserkin** [comment]
@johnpapa but from your point of view should those names (in camelCase) start with capital leter or by (camelCase) you answered, that start with lower later (as some object property)?

**Comment by johnpapa** [comment]
camelCase is a lowercase letter first.
