### ISSUE TITLE
more testing organization

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angularjs-styleguide#79]

**Comment by dbabaioff** [comment]
Also, it would be nice to have a section explaining how to organize the test files into different folders and how to name the files.

**Comment by johnpapa** [comment]
@dbabaioff I updated that here bf6194211327367cbb9f56794a5d7aa0ad771eff

**Comment by DieterAtWork** [comment]
@dbabaioff, We use the same folders as our application and just add .spec.js to the original filenames. We find this very clear.
